name: joya_auth
description: Token secure storage and memory cache for Joya Flutter kits.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
